language: node_js
node_js:
  - "12.8.1"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t valyou-web .
  - docker tag valyou-web registry.heroku.com/valyou/web

deploy:
  provider: script
  script: 
    docker push registry.heroku.com/valyou/web;
    heroku container:release web --app valyou
  on:
    branch: master